# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Style configurations
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

# Layout configurations
Layout/LineLength:
  Max: 120

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics configurations
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

# Bundler configurations
Bundler/OrderedGems:
  Enabled: true

# Rails configurations
Rails:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: slashes

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict
